### ISSUE TITLE
remove unused prefect-related functions

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/DDP_backend#542]
## Description
The codebase contains deprecated code which needs to be removed. As a first step towards this, remove the functions by following the sheet 

https://docs.google.com/spreadsheets/d/1sgh5NtW8MEcYiUcs9GaojtqsTR2Vk_zpX5bF4ef6zzs/edit#gid=0

## Goals
- [ ] Remove unused functions 
- [ ] Remove related tests

## Expected Outcome
The program should still work, all tests should pass

## Acceptance Criteria
- [ ] Should follow the Google Sheet listed above
- [ ] Tests should pass

## Implementation Details
No new code is to be added

## Mockups / Wireframes
N/A

### Product Name
Dalgo

### Project Name
Dalgo

### Organization Name:
Project Tech4Dev

### Domain
30 Others

### Tech Skills Needed:
Python

### Mentor(s)
@fatchat 

### Complexity
Low

### Category
Performance Improvement

### Sub Category
Backend, Deprecation, Technical Debt, Beginner friendly

**Comment by kauxp** [comment]
@fatchat I want to work on this issue. As per my understanding, we have to remove the checked functions in the Excel sheet. Please correct me if I am wrong else I will proceed with the pull request.

**Comment by fatchat** [comment]
@kauxp yes you're correct... but give me a few days to spec out the issue

you can start by verifying what i put into the sheet. when i tag it as "c4gt community" you'll know it's ready to be worked on

**Comment by kauxp** [comment]
@fatchat could you please tell me why are the tests failing?

**Comment by fatchat** [comment]
@kauxp the github tests fail for you because of how we have (mis)configured our github actions... you and ishan are already talking about this in your prefect-proxy PR

you should be able to run them locally *if* you run a local Airbyte

**Comment by fatchat** [comment]
Also for deletion:
- `create_shell_block_for_migration`
- `run-tasks-migrate-cmd`
- `set_uuids_in_orgtask_deployment`

**Comment by fatchat** [comment]
@kauxp now that the prefect-proxy PR has been merged you can start on this if you want to

**Comment by SreeCharan1234** [comment]
@fatchat  i want to work on this issue  as i have a good knowledge of python i can remove all the functions

**Comment by kauxp** [comment]
Sure, I will be happy to complete this issue, as I understand since we have deleted the unused functions from prefect-proxy codebase now we need to remove all the functions from DDP_backend which calls those removed functions, correct? 

2. for `create_shell_block_for_migration`, `run-tasks-migrate-cmd` and `set_uuids_in_orgtask_deployment` do we need to delete the complete file?

3. I checked the [sheet](https://docs.google.com/spreadsheets/d/1sgh5NtW8MEcYiUcs9GaojtqsTR2Vk_zpX5bF4ef6zzs/edit#gid=0) again and found I missed 2 endpoints to remove in my previous PR, `/proxy/blocks/dbtcore/` and `/proxy/blocks/dbtcore_edit/{wtype}/`. 
for `/proxy/blocks/dbtcore_edit/{wtype}/` do we need to remove 
- https://github.com/DalgoT4D/prefect-proxy/blob/1ce1d5afad68ef51c0aeb6cdc2982ec5aa7ce3fb/proxy/main.py#L267C14-L267C38
- https://github.com/DalgoT4D/prefect-proxy/blob/1ce1d5afad68ef51c0aeb6cdc2982ec5aa7ce3fb/proxy/main.py#L285

**Comment by fatchat** [comment]
@SreeCharan1234 , I would usually encourage you to do this but @kauxp has already started on this exercise so I was going to let just them complete it

**Comment by kauxp** [comment]
> Sure, I will be happy to complete this issue, as I understand since we have deleted the unused functions from prefect-proxy codebase now we need to remove all the functions from DDP_backend which calls those removed functions, correct?
> 
> 2. for `create_shell_block_for_migration`, `run-tasks-migrate-cmd` and `set_uuids_in_orgtask_deployment` do we need to delete the complete file?
> 3. I checked the [sheet](https://docs.google.com/spreadsheets/d/1sgh5NtW8MEcYiUcs9GaojtqsTR2Vk_zpX5bF4ef6zzs/edit#gid=0) again and found I missed 2 endpoints to remove in my previous PR, `/proxy/blocks/dbtcore/` and `/proxy/blocks/dbtcore_edit/{wtype}/`.
>    for `/proxy/blocks/dbtcore_edit/{wtype}/` do we need to remove
> 
> * https://github.com/DalgoT4D/prefect-proxy/blob/1ce1d5afad68ef51c0aeb6cdc2982ec5aa7ce3fb/proxy/main.py#L267C14-L267C38
> * https://github.com/DalgoT4D/prefect-proxy/blob/1ce1d5afad68ef51c0aeb6cdc2982ec5aa7ce3fb/proxy/main.py#L285

@fatchat could you please clear the doubts?

**Comment by fatchat** [comment]
@kauxp i'll remove those prefect-proxy endpoints as part of some other PR

regarding the deprecated management commands... let's move them to a subfolder called `management/commands/deprecated/`

**Comment by asengupta07** [comment]
Hey @fatchat, I would like to work on this issue if it is still open. I have worked on django project before and have a good understanding of python, so I am certain I will be able to help.

**Comment by anandamideShakyan** [comment]
I want to work on this issue. Is it still open?

**Comment by fatchat** [comment]
@kauxp are you still doing this or can we open it up for others?

**Comment by SreeCharan1234** [comment]
Open it for others

**Comment by fatchat** [comment]
Opening this up for everyone

**Comment by kauxp** [comment]
Hello, I apologize for the delay in my work, but I was facing some unexpected challenges.

I have made the PR can you review this and let me know if something is there to be updated.

**Comment by Akshat-Jaiswal-8** [comment]
Is there anything left in this @fatchat ?

**Comment by fatchat** [comment]
@Akshat-Jaiswal-8 yes if you want to work on it go ahead

**Comment by Rishikesh63** [comment]
@fatchat  can i work on this project? i setup partially DDP_bakend and also submitted proposals for DMP project of dalgo.

**Comment by Rishikesh63** [comment]
@fatchat 
uvicorn proxy.main:app --workers 4 --host 0.0.0.0 --port 8001
after running this command i get error:-

INFO: Uvicorn running on http://0.0.0.0:8001/ (Press CTRL+C to quit)
INFO: Started parent process [20052]
Process SpawnProcess-3:
Process SpawnProcess-2:
Process SpawnProcess-1:
Process SpawnProcess-4:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
File "C:\Users\User.pyenv\pyenv-win\versions\3.10.11\lib\multiprocessing\process.py", line 314, in _bootstrap
self.run()
File "C:\Users\User.pyenv\pyenv-win\versions\3.10.11\lib\multiprocessing\process.py", line 314, in _bootstrap
self.run()
File "C:\Users\User.pyenv\pyenv-win\versions\3.10.11\lib\multiprocessing\process.py", line 314, in _bootstrap
self.run()
File "C:\Users\User.pyenv\pyenv-win\versions\3.10.11\lib\multiprocessing\process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "C:\Users\User.pyenv\pyenv-win\versions\3.10.11\lib\multiprocessing\process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "C:\Users\User.pyenv\pyenv-win\versions\3.10.11\lib\multiprocessing\process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn_subprocess.py", line 76, in subprocess_started
target(sockets=sockets)
Traceback (most recent call last):
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn_subprocess.py", line 76, in subprocess_started
target(sockets=sockets)
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn_subprocess.py", line 76, in subprocess_started
target(sockets=sockets)
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\server.py", line 59, in run
return asyncio.run(self.serve(sockets=sockets))
File "C:\Users\User.pyenv\pyenv-win\versions\3.10.11\lib\asyncio\runners.py", line 44, in run
return loop.run_until_complete(main)
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\server.py", line 59, in run
return asyncio.run(self.serve(sockets=sockets))
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\server.py", line 59, in run
return asyncio.run(self.serve(sockets=sockets))
File "C:\Users\User.pyenv\pyenv-win\versions\3.10.11\lib\multiprocessing\process.py", line 314, in _bootstrap
self.run()
File "C:\Users\User.pyenv\pyenv-win\versions\3.10.11\lib\multiprocessing\process.py", line 108, in run
self._target(*self._args, **self.kwargs)
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn_subprocess.py", line 76, in subprocess_started
target(sockets=sockets)
File "C:\Users\User.pyenv\pyenv-win\versions\3.10.11\lib\asyncio\runners.py", line 44, in run
return loop.run_until_complete(main)
File "C:\Users\User.pyenv\pyenv-win\versions\3.10.11\lib\asyncio\base_events.py", line 649, in run_until_complete
return future.result()
File "C:\Users\User.pyenv\pyenv-win\versions\3.10.11\lib\asyncio\runners.py", line 44, in run
return loop.run_until_complete(main)
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\server.py", line 59, in run
return asyncio.run(self.serve(sockets=sockets))
File "C:\Users\User.pyenv\pyenv-win\versions\3.10.11\lib\asyncio\base_events.py", line 649, in run_until_complete
return future.result()
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\server.py", line 66, in serve
config.load()
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\config.py", line 471, in load
self.loaded_app = import_from_string(self.app)
File "C:\Users\User.pyenv\pyenv-win\versions\3.10.11\lib\asyncio\runners.py", line 44, in run
return loop.run_until_complete(main)
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\server.py", line 66, in serve
config.load()
File "C:\Users\User.pyenv\pyenv-win\versions\3.10.11\lib\asyncio\base_events.py", line 649, in run_until_complete
return future.result()
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\importer.py", line 24, in import_from_string
raise exc from None
File "C:\Users\User.pyenv\pyenv-win\versions\3.10.11\lib\asyncio\base_events.py", line 649, in run_until_complete
return future.result()
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\config.py", line 471, in load
self.loaded_app = import_from_string(self.app)
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\server.py", line 66, in serve
config.load()
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
module = importlib.import_module(module_str)
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\server.py", line 66, in serve
config.load()
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\importer.py", line 24, in import_from_string
raise exc from None
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\config.py", line 471, in load
self.loaded_app = import_from_string(self.app)
File "C:\Users\User.pyenv\pyenv-win\versions\3.10.11\lib\importlib_init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\config.py", line 471, in load
self.loaded_app = import_from_string(self.app)
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
module = importlib.import_module(module_str)
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\importer.py", line 24, in import_from_string
raise exc from None
File "", line 1050, in gcd_import
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\importer.py", line 24, in import_from_string
raise exc from None
File "C:\Users\User.pyenv\pyenv-win\versions\3.10.11\lib\importlib_init.py", line 126, in import_module
return _bootstrap.gcd_import(name[level:], package, level)
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
module = importlib.import_module(module_str)
File "C:\Users\User.pyenv\pyenv-win\versions\3.10.11\lib\importlib_init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1050, in _gcd_import
File "", line 1050, in _gcd_import
File "", line 1027, in _find_and_load
File "C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
module = importlib.import_module(module_str)
File "", line 1027, in _find_and_load
File "", line 1027, in _find_and_load
File "", line 1006, in find_and_load_unlocked
File "C:\Users\User.pyenv\pyenv-win\versions\3.10.11\lib\importlib_init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1050, in _gcd_import
File "", line 1027, in _find_and_load
File "", line 688, in _load_unlocked
File "", line 883, in exec_module
File "", line 1006, in _find_and_load_unlocked
File "", line 688, in _load_unlocked
File "", line 1006, in _find_and_load_unlocked
File "", line 241, in _call_with_frames_removed
File "", line 1006, in _find_and_load_unlocked
File "", line 883, in exec_module
File "", line 688, in _load_unlocked
File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\main.py", line 9, in
from proxy.service import (
File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\service.py", line 36, in
from proxy.prefect_flows import deployment_schedule_flow_v4
File "", line 241, in _call_with_frames_removed
File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\main.py", line 9, in
from proxy.service import (
File "", line 688, in _load_unlocked
File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\prefect_flows.py", line 11, in
from prefect_airbyte.flows import reset_connection
File "", line 883, in exec_module
ImportError: cannot import name 'reset_connection' from 'prefect_airbyte.flows' (C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\prefect_airbyte\flows.py)
File "", line 883, in exec_module
File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\service.py", line 36, in
from proxy.prefect_flows import deployment_schedule_flow_v4
File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\prefect_flows.py", line 11, in
from prefect_airbyte.flows import reset_connection
File "", line 241, in _call_with_frames_removed
File "", line 241, in _call_with_frames_removed
ImportError: cannot import name 'reset_connection' from 'prefect_airbyte.flows' (C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\prefect_airbyte\flows.py)
File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\main.py", line 9, in
from proxy.service import (
File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\service.py", line 36, in
from proxy.prefect_flows import deployment_schedule_flow_v4
File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\prefect_flows.py", line 11, in
from prefect_airbyte.flows import reset_connection
ImportError: cannot import name 'reset_connection' from 'prefect_airbyte.flows' (C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\prefect_airbyte\flows.py)
File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\main.py", line 9, in
File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\service.py", line 36, in
from proxy.prefect_flows import deployment_schedule_flow_v4
File "C:\Users\User\Desktop\DMP\prefect-proxy\proxy\prefect_flows.py", line 11, in
from prefect_airbyte.flows import reset_connection
ImportError: cannot import name 'reset_connection' from 'prefect_airbyte.flows' (C:\Users\User\Desktop\DMP\DDP_backend\venv\lib\site-packages\prefect_airbyte\flows.py)

please guide me how i can solve this problem

**Comment by decembboy** [comment]
I wish to tackle this problem.

**Comment by fatchat** [comment]
@decembboy please go ahead. the issue is a bit old and i don't know how many unused functions remain, but i'm sure there are some

**Comment by decembboy** [comment]
> @decembboy please go ahead. the issue is a bit old and i don't know how many unused functions remain, but i'm sure there are some

I removed  unnecessary routines related to perfect; could you kindly check?

https://docs.google.com/spreadsheets/d/1sgh5NtW8MEcYiUcs9GaojtqsTR2Vk_zpX5bF4ef6zzs/edit?usp=sharing

**Comment by decembboy** [comment]
> @decembboy please go ahead. the issue is a bit old and i don't know how many unused functions remain, but i'm sure there are some

i remove unused prefect-related functions, could you kindly verify?

https://docs.google.com/spreadsheets/d/1sgh5NtW8MEcYiUcs9GaojtqsTR2Vk_zpX5bF4ef6zzs/edit?usp=sharing

**Comment by kesharibhai84** [comment]
hi @fatchat, i want to work on this issue. Please assign me this one

**Comment by fatchat** [comment]
hi @kesharibhai84 when you raise a PR i'll review it and if it passes i'll merge it

**Comment by kesharibhai84** [comment]
@fatchat if im not wrong we have remove the the one which is marked in column A,
and can you explain little bit about Column E and F,
Im getting consfused

**Comment by fatchat** [comment]
@kesharibhai84 columns E and F provide a partial caller graph

**Comment by Blacksujit** [comment]
@fatchat  

can i work on this  issue.

**Comment by trishanu-init** [comment]
@fatchat i would like to work on this issue.

**Comment by yashpal2104** [comment]
Hey @@fatchat there seems to require an edit access if you provide it to me I can remove the ticked function which are not required

**Comment by VedantKhairnar** [comment]
@yashpal2104 @trishanu-init 
Will you pls explain the approach? This will help Rohit to assign the issue.
Feel free to directly raise PR if you see fit.
Thanks.

**Comment by yashpal2104** [comment]
1. I will review the sheet to look at which deprecated functions are to be removed. Check if there are any dependencies which require this functions.
2. I will search the codebase using IDE search to exactly go to the function. Check if it is being used elsewhere in the codebase 
3. First comment out the function to see if it runs then remove testcases and associated code 
4. Run tests to see if everything works properly then get my code reviewed and then commit changes
This is how I will approach this problem please do correct me if there is something else I need to do I will work on it.

**Comment by fatchat** [comment]
@yashpal2104 the problem is step (3) doesn't give you a strong guarantee since python is an interpreted language

**Comment by yashpal2104** [comment]
So what I can do is:
1. Refactor the code gradually replace with alternatives
2. Error handling, unit tests, integrating test, use pylint or mypy(although I don't know about these but I can learn)

What do you think about this approach

**Comment by fatchat** [comment]
@yashpal2104 i think text-searching for the function name is a good way to start, if you find a caller then search for the caller... etc. sometimes you will find there is no "entry point" to the chain and this means the entire chain can be removed from the codebase

an "entry point" would be either a) an api endpoint, or b) a management command (i.e. a script)

and yes of course you should run it and see if tests pass as well

fair warning: i haven't looked at the spreadsheet in months, don't know how up-to-date it is

**Comment by yashpal2104** [comment]
Sure I will do the same. Thanks a lot for your help

**Comment by yashpal2104** [comment]
Can anyone get me started to get onboard with the workflow for this repo I want to contribute to. I am a beginner here and it would really help me if anyone who is familiar with this repo can guide on what steps should I follow to raise my PR to solve this issue.

**Comment by huzaifmalik786** [comment]
Hey @yashpal2104 , can you share me your discord id. I'll share you some steps to setup the codebase.
Thanks!

**Comment by Amrit02102004** [comment]
Is it still open to work on ?
I want to contribute in this

**Comment by VedantKhairnar** [comment]
hey @Amrit02102004 
Yes, it is. Please directly raise the PR.
Do let us know if you have any queries. Thanks.

**Comment by Amrit02102004** [comment]
@hp770creator did you fix the issue ? Should I still work on it?

**Comment by hp77-creator** [comment]
Hi @Amrit02102004 
Yes I have removed the unused endpoints.
